### ISSUE TITLE
주제 선정

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#1]
오픈소스 프로젝트 주제 정하기

**Comment by snsthqhr** [comment]
### 기분, 현재 무드, 하고있는 행동등을 입력 받아 플레이리스트 만들어주기

- 플레이리스트를 만들어서 추천해주는 서비스는 많지만 구체적으로 날씨, 오늘의 기분, 하고있는 행동들을 고려해서 노래 플레이리스트를 만들어주는 것이 따로 없음
- 단순히 노래를 추천해주는 것이 아닌 현재 시간을 기준으로 밤이냐 아침이냐, 기분, 장르 행동 정보에 따라 다른 노래들로 구성된 플레이리스트를 추천해줌

**Comment by eunseongy** [comment]
사람 몸 상태 예측을 통해 각자에게 필요한 영양제 종류를 추천하고 거기에 더해 브랜드마다 가격이나 품질 등 특성이 다른 데 이 사람이 어떤 것에 중점을 두는 지에 따라 적합한 영양제 브랜드 추천은 어떨까요?

**Comment by mondayy1** [comment]
**지출 예상 서비스**

1. 저번 달 한달간의 지출 내역을 입력하면 다음달 지출 예측해서 알려주는 서비스
2. 줄이고 싶은 분야의 지출을 확인해서 알려줌, 지출 내역을 알려주는 서비스는 있지만 분야별(음식, 옷, 쇼핑, 등) 어떤 곳에 사용했는지 알려주는 서비스는 없음
