### ISSUE TITLE
Final presentation 한계점, 개선방향

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#100]
배점 기준표를 보면 한계점, 개선방향이 있는데, 이 내용의 구성을 어떻게 할까요?
제가 생각한 안으로는 
1. 사이트의 디자인 
2. 추천 영양제의 종류
3. 결과 페이지의 시각적 정보 전달력 

이정도 생각중입니다

**Comment by eunseongy** [comment]
네 1번과 3번이 겹치는 것 같습니다. 그리고 2번에 chatgpt에 의존한 정보전달로 묶으면 어떨까요?

**Comment by snsthqhr** [comment]
1,3 번묶었습니다
