### ISSUE TITLE
제가 생각한 설문 조사 목록 입니다.

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#16]
추가 해야 할 것이나 더 필요한 질문이 있다면 여기에 올려주세요. 
------------------------------------------------------------------------------------------------------------------------------------------
구강 건강
구내염, 입술의 통증, 입술이 자주 갈라진다.
입냄새가 심하다.

소화 관련
소화가 잘 되지않는다.
복부 팽만이 심하다.
설사나 변비가 잦다.
치질이 있다.

몸 컨디션
평상시 기운이 없다.
모발이 얇아지거나 머리가 자주 빠진다.
쉽게 피곤해진다.
빈혈, 어지러움 증상이 있다.
술을 자주 마신다
면역력이 떨어지는거 같다.
수족냉증이 있다.
피부 트러블이 잦다.

통증 관련
어깨가 자주 뭉친다.
근육통,쥐가 자주 난다.
타박상을 입었을때 피부가 쉽게 멍이 든다.
편두통이 심하다.

**Comment by snsthqhr** [comment]
추가적으로 안구 관련질문
1. 눈이 자주 침침해진다.
2. 안구 건조증이 있다.
3. 시야가 자주 흐려진다.
4. 시력이 좋지 않다.
위 4가지 추가했습니다. 제가 작성할 설문에서 빼고싶은게 있다면 말해주세요.

**Comment by mondayy1** [comment]
칼슘관련한 영양제가 많은데 뼈 관련한 설문도 있으면 좋겠어요!!

**Comment by snsthqhr** [comment]
> 칼슘관련한 영양제가 많은데 뼈 관련한 설문도 있으면 좋겠어요!!

확인했습니다! 추가 해볼게요!

**Comment by eunseongy** [comment]
몸 컨디션에 '식욕이 없다'를 추가하면 좋을 거 같고 '면역력이 약해지는 것 같다'보단 감기에 쉽게 걸린다'라는 설문조사 하는 사람에겐 더 와닿을 거 같아요!

**Comment by snsthqhr** [comment]
> 몸 컨디션에 '식욕이 없다'를 추가하면 좋을 거 같고 '면역력이 약해지는 것 같다'보단 감기에 쉽게 걸린다'라는 설문조사 하는 사람에겐 더 와닿을 거 같아요!

면역력이 약해지는 것 같다.라는 문장은 확실히 사용자가 느끼기에 막연할거 같네요. 수정해서 감기에 쉽게 걸린다로 수정하도록 할게요.
식욕이 없다의 경우 영양성분부족문제가 아니라고 생각해서 따로 넣지는 않았습니다

**Comment by snsthqhr** [comment]
질문 수정 최종적으로 마무리되었으므로 이슈 닫겠습니다
