### ISSUE TITLE
서비스 방식/ 모델 선정

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#2]
서비스 방식과 모델 선정은 어떤 걸로 할까요?

**Comment by snsthqhr** [comment]
많은 사람들이 쉽게 접근 할 수 있도록 앱으로 만들어서 제공하는걸 어떨까요?

**Comment by mondayy1** [comment]
앱도 접근성이 좋긴한데 웹사이트로 구현하는게 좋을거같습니다. 앱으로 구현했을 때 플랫폼(안드, aos, 하이브리드)에 따라서 다르게 구현해야하는 어려움이 있어서 힘들거같아요.

**Comment by eunseongy** [comment]
스위프트나 오브젝트-C같은 거로 구현하는 건 어떨까요?

**Comment by snsthqhr** [comment]
> 앱도 접근성이 좋긴한데 웹사이트로 구현하는게 좋을거같습니다. 앱으로 구현했을 때 플랫폼(안드, aos, 하이브리드)에 따라서 다르게 구현해야하는 어려움이 있어서 힘들거같아요.

듣고보니 swift나 안드로이드 스튜디오를 다룰수 있는 사람이 없어서 무리가 있는거 같네요. 웹사이트로 구현하는걸로 하죠.

**Comment by eunseongy** [comment]
넵 좋은 것 같아요

**Comment by mondayy1** [comment]
그러면 요즘 챗gpt가 최신기술에다가 오픈소스니까 챗gpt api를 이용해서 예측 모델을 구현하는건 어떨까요

**Comment by snsthqhr** [comment]
> 그러면 요즘 챗gpt가 최신기술에다가 오픈소스니까 챗gpt api를 이용해서 예측 모델을 구현하는건 어떨까요

저희가 직접 정보를 전부 입력 받아서, 구현하기에는 무리가 있어보이니 chat gpt를 이용해서 정보를 처리 해주는 방식 좋은거 같습니다. 저희는 정보 입력 받고, 사용자에게 결과값을 알려주는 ui위주로 신경 써서 하면 좋을거 같아요.
