### ISSUE TITLE
진단 결과 사이트 디자인

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#22]
![image](https://user-images.githubusercontent.com/128560366/232309474-8d7705ed-a0a1-46f8-ad1f-9b3a09eca749.png)

현재 페이지로 간단하게 디자인 했고 오른쪽에는 추천하는 영양제들 이미지를 넣으려고 합니다. 혹시 디자인적으로 필요한 거 있으시면 말해주세요~

**Comment by snsthqhr** [comment]
배경이미지 바꿔보는거 어떨가요? 뭔가 배경이미지 때문에 앞에 글씨가 잘 보이지 않는거 같아서 가독성이 좀 떨어지는거 같아요

**Comment by eunseongy** [comment]
오 좋은 거 같아요 참고할게요
