### ISSUE TITLE
중간발표 대본

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#27]
![image](https://user-images.githubusercontent.com/128250130/232992805-d1fa0fbf-f7ed-43c7-84d1-aaec400c1255.png)
영샹보면서 말할겁니당

**Comment by snsthqhr** [comment]
발표 대본 초반입니다.


안녕하세요  
이번에 오프소스 프로젝트 여장신조 중간 발표를 맡게된 xxx입니다.
(저희 조에 대하여 간략하게 소개한다면, 팀 명은 여장신이고, 팀원으로는 여은성 장호중 신동우 입니다.)
 저희가 이번 프로젝트에서 구현한 프로그램은 영양제 추천 서비스입니다.
 사용자로부터 현재 몸상태에 대하여 물어본뒤 사용자가 응답한 답을 토대로, 어떤 영양성분이 부족한지, 이 영양성분을 보충하기 위해서 어떤 영양제를 섭취하는 것이 좋은지를 알려주는 것을 만들려고 합니다.
저희가 이 주제를 선정하게 된 이유는 현대인의 대부분은 칼슘, 비타민등과 같이 필수 영양소인 영양 성분들을 섭취 하지 못하는 경우가 많습니다. 특히 저희 같은 학생의 경우, 이런 영양성분을 섭취 하지 못하는 경우가 많습니다. 섭취하려고 조사를 해봐도, 명확하게 무슨 영양제를 어떻게, 얼마나 많이 섭취해야하는지 자신에 맞게 조사하기 힘듭니다. 저희는 이런 과정에 도움을 드리고자 여장신 영양제 추천 서비스를 만들게되었습니다.

 이미 시중에는 사용자의 건강상태를 입력 받아서 영양제를 추천해주는 서비스가 많이 있습니다.  
 대표적인 예로 필리라는 영양제 추천 서비스를 제공하는 영양제 판매 사이트가 있습니다. 이 사이트는 사용자로부터 건강상태에 대하여 설문을 한 뒤 그 설문을 기반으로 ai를 통해자사의 영양제들을 추천해주는 영양제 추천 서비스를 제공하고 있습니다. 이 사이트는 영양제를 추천할 때 자사의 영양제만 추천해 줄 뿐, 폭 넓은 추천을 해주지는 않습니다. 또 영양제의 영양성분에 따라서 영양제를 어떻게 ,얼마나 복용할지는 알려주지 않습니다.
저희는 기존 영양제 추천 서비스와 차별점으로 폭넓은 영양제 추천과, 사용자의 식습관등을 고려해서 영양제의 복용시간, 한번에 섭취하는 영양제의 양, 건강 개선을 위해 추천하는 활동, 개선방향 등을 같이 고려해서 추천해주려고 합니다.


저희는 여장신 영양제 추천 서비스를 웹페이지를 통해 사용자에게 제공 하려 합니다. 홈페이지를 제공할 때는, html을 사용하였으며, 웹프레임 워크로는 파이썬의 장고를 이용하였습니다

**Comment by snsthqhr** [comment]
### 1~5번까지의 발표 대본입니다.
초안에서 매끄럽지 않은 문장 다듬었습니다.

안녕하세요 
이번에 오프소스 프로젝트 여장신조 중간 발표를 맡게된 xxx입니다.
(저희 조에 대하여 간략하게 소개한다면, 팀 명은 여장신이고, 팀원으로는 여은성 장호중 신동우 입니다.)
 저희가 이번 프로젝트에서 구현한 프로그램은 영양제 추천 서비스입니다.
 사용자로부터 현재 몸상태에 대하여 물어본뒤 사용자가 응답한 답을 토대로, 어떤 영양성분이 부족한지, 이 영양성분을 보충하기 위해서 어떤 영양제를 섭취하는 것이 좋은지를 알려주는 것을 만들려고 합니다.
현대인의 식생활을 들여다보면, 열량은 넘쳐나지만, 정작 우리 몸에 필요한 비타민과 미네랄과 같은 성분은 부족한 경우가 많습니다. 특히 저희 같은 학생의 경우, 배달음식이나, 패스트 푸드를 굉장히 많이 먹습니다. 그러면 다양한 양질의 영양분을 섭취 하지 못합니다(애드립 plz). 굳이 챙겨먹으려고 해봐도 명확하게 무슨 영양제를 얼마나, 어떻게 섭취 해야하는지 알기가 힘듭니다. 저희는 이런 문제를 해결하고자 여장신 영양제 추천 서비스를 만들게 되었습니다.

 이미 시중에는 사용자의 건강상태를 입력 받아서 영양제를 추천해주는 서비스가 많이 있습니다.  
 대표적인 예로 필리라는 서비스가 있습니다. 이 사이트는 사용자로부터 건강상태에 대하여 설문을 한 뒤 그 설문을 기반으로 ai를 통해자사의 영양제를 추천해줍니다. 이 사이트는 영양제를 추천할 때 자사의 제품만 추천해 줄 뿐, 선택의 기회를 제공하지 않습니다. 또 영양제의 영양성분에 따라서 얼마나, 어떻게 복용할지는 제시하지 않습니다. 그렇기 때문에 ,저희는 기존 영양제 추천 서비스와 차별점으로써 사용자의 식습관, 영양제의 복용시간, 일일 권장 섭취량, 개선방향 등을 같이 고려해서 추천해주려고 합니다.


이 서비스는 웹페이지를 통해 사용자에게 제공 하려 합니다. 앱으로 하는게 더 접근성이 좋겠지만, 저희가 아직 그 부분에는 많이 미숙해서, 배우기 쉬운 html과, 웹프레임 워크인 장고를 이용하였습니다.

**Comment by snsthqhr** [comment]
### Ppt 10 ~ 11
 앞으로의 구현 방향은 ppt에서  보는 바와 같습니다.
아직 웹사이트에서 기본적인 기능만 구현했을 뿐, 보는데 불편함이 굉장히 많이 있습니다. 이것을 보완하여서 디자인을 완성시키겠습니다.
 식습관을 고려해서 사용자에게 영양제 추천을 해주는 것이 저희의 차별점 요소인데 아직 설문지에는 사용자의 식습관 관련된 질문이 없습니다. 따라서 설문지 페이지에 사용자의 식습관과 관련된 질문을 추가하고, 추가된 질문들을 토대로 영양소별로 영양제 추천과, 복용방법 ,1일 권장 섭취량을 추천하겠습니다.

중간 발표 이후에 계획에 대하여 설명해 드리겠습니다. 5월에는 서비스 구현 완료를 목표로 하고 있습니다. 5월중으로 디자인작업, 설문추가, 결과 출력을 전부 완료하고 6월에는 시스템의 에러를 잡고, fix해서 프로그램을 안정화를 하려고 합니다.

**Comment by mondayy1** [comment]
1차 마무리 대본임니다
https://docs.google.com/document/d/1kY7ZBj0kkfJNReCvXaAABJuH_fPTfXlUBoQb6mG9-Yc/edit
