### ISSUE TITLE
Mid term 중간 발표 PPT

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#28]
[Mid-term-presentation.jpg.zip](https://github.com/snsthqhr/opensauce/files/11270373/Mid-term-presentation.jpg.zip)

**Comment by eunseongy** [comment]
보완할 점 있으면 말해주세요!

**Comment by eunseongy** [comment]
[Mid-term-presentation.jpg (2).zip](https://github.com/snsthqhr/opensauce/files/11271441/Mid-term-presentation.jpg.2.zip)
수정한 ppt입니다.

**Comment by mondayy1** [comment]
[Mid-term presentation (1).pptx](https://github.com/snsthqhr/opensauce/files/11271504/Mid-term.presentation.1.pptx)

**Comment by snsthqhr** [comment]
ppt 최종본 블랙보드에 업로드 하였고, 대본이랑 최종적으로 맞춰보았습니다. 이슈 닫겠습니다.
