### ISSUE TITLE
챗GPT를 이용하는 다른 서비스들과의 차별성 두기

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#3]
**주제**
영양제 추천 서비스

**차별성**
보통 메디컬 관련 앱이나 영양제 추천 앱에서는 진단과 제품 추천이 개별적으로 이루어졌습니다.
저희는 여기서 사용자의 진단과 제품추천의 과정을 하나로 합치면서 챗GPT를 이용하면 좋을거같습니다.
EX) 사용자가 체크리스트를 통해서 설문지 형식으로 본인의 상태 기술 -> 이에 기반하여 GPT에게 질문 -> 필요 영양소를 진단받고
저희가 만든 영양제 데이터베이스에서 필요한 영양제를 추천 받는식
대표적인 한국의 영양제 추천 앱인 필라이즈에서는 후기나 판매량을 기반으로 해서 영양제 제품을 추천해줍니다.

**Comment by eunseongy** [comment]
말씀하신 필라이즈에서는 본인의 상태에 따라 추천하는 것과 필요 영양소를 입력했을 때 따로따로 추천하므로 이거를 한 번에 묶어서 추천하는 방법은 이용자 입장에서는 간편하고 원래 있던 사이트와는 차별성이 있을 것 같아서 좋아요!
