### ISSUE TITLE
홈페이지 디자인 수정

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#34]
홈페이지 디자인을 전체적으로 수정하려고 합니다. 
![image](https://github.com/snsthqhr/opensauce/assets/128560366/cd787518-0972-43b1-82c7-cac54ef555ef)
위의 사진처럼 위의 클릭 부분을 만들고 배경 이미지도 변경하겠습니다.

**Comment by snsthqhr** [comment]
큰 틀 정해주시면 조사 페이지에도 비슷하게 적용 하겠습니다. 금요일에 만나서 직접 얘기하면서 진행하면 좋을듯 합니다

**Comment by snsthqhr** [comment]
디자인 통일했습니다. 이슈닫겠습니다
