### ISSUE TITLE
영양소와 영양제 추천 받는 갯수 수정

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#36]
영양소 5개는 너무 적은것 같습니다. 10개로 하는건 어떤가요?
대신에 영양소별 영양제는 3->2개로 줄입시다!!

**Comment by eunseongy** [comment]
영양소 10개는 너무 많아서 난잡해질 것 같습니다. 대신 영양소 3개 정도여도 충분할 것 같습니다.
