### ISSUE TITLE
영양소에 따라 영양제 추천

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#38]
1. 유산균
2. 마그네슘
3. 철분
4. 칼슘
5. 오메가-3
6. 종합비타민
 각 영양소에 대해서 함유량 많은 영양제와 적은 영양제를 하나씩 조사하고 섭취 시기 등을 올리겠습니다.

**Comment by snsthqhr** [comment]
조사후에 내용정리해서 이슈 하나 만들어주세요
코드 짜는데 참고하겠습니다.

**Comment by mondayy1** [comment]
넵
