### ISSUE TITLE
진단결과페이지 초안 만들었습니다.

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#39]
![image](https://github.com/snsthqhr/opensauce/assets/74997069/9f11c389-b936-4a91-918a-fcc34fce1357)
일단 어느정도 완성했는데, 일단 메인으로 머지 한번 할까요?

**Comment by mondayy1** [comment]
좋습니다!!
근데 사이즈를 조금만 줄였으면 좋겠어요...

**Comment by snsthqhr** [comment]
어떤사이즈 말씀하시는건가요
