### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#4]
**주요 기능**
1. 건강 진단 체크리스트(설문지)
2. 설문지를 챗GPT에게 질문할 하나의 문장으로 만들기
3. 챗GPT API이용해서 필요한 영양소를 진단받는 기능
4. 챗GPT의 응답에서 필요한 정보 추출
5. 영양소 DB작성
6. DB에서 영양소 + 부가정보를 통해서 제품 선정
7. 선정된 제품을 사용자에게 보여주기

대충 이정도 기능을 구현하면 서비스가 완성 될 거 같습니다.

**Comment by snsthqhr** [comment]
건강 진단 체크리스트(설문지 작성), 설문지를 chat gpt에게 질문한 하나의 문장으로 만들기,chat gpt api이용해서 필요한 영양소를 진단받는 기능 구현을 제가 맡을게요!
 체크리스트를 웹페이지에 구현 할때, 부위, 증상 별로 묶어서 구현 할게요.

**Comment by eunseongy** [comment]
동우님이 만드신 체크리스트를 토대로 세분화 했을 때 챗GPT에게 질문할 하나의 문장으로 만들고 챗GPT에서 필요한 정보 추출하는 것을 해볼게요.

**Comment by mondayy1** [comment]
그럼 저는 영양제 DB 초안 준비해 놓겠습니다.

**Comment by mondayy1** [comment]
공부를 해보니까 이런식으로는 택도 없을것같습니다.

프론트 / 백 부분으로 최대한 나눠서 진행하는걸로 합시다.

제가 gpt와 communicate하는 기능적인 부분을 주로 구현 해 보겠습니다.

**Comment by eunseongy** [comment]
제가 프론트 부분 중에서 메인 웹사이트를 구현해 보겠습니다.
