### ISSUE TITLE
영양제 조사 내용

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#40]
1. 유산균
-권장량
1일 평균 권장 섭취량은 1억~100억마리로 꾸준히 섭취하는 것이 중요

- 섭취시간
유산균은 위산이나 담즙산에 쉽게 죽는 특성이 있는데 식사를 함ㄴ 위산 분비가 늘어나므로 아침 공복 시간에 가장 좋고 잠들기 전에 섭취해도 된다. 

- 헬시오리진스 내추럴 프로바이오틱 유산균 
1캡슐당 300억의 보장균 수로 많은 편

- 서울약사신협 프로바이오 생유산균
1포당 총 1억의 보장균 수로 적은 편

2.마그네슘
-권장량
마그네슘 일일 섭취 권장량은 성인의 경우 남성은 350~370mg이고 여성은 280mg이다.

-섭취시간
심신 안정 효과가 있어 숙면에 도움이 되므로 저녁 식후나 자기 전에 복용하는 것이 좋다.

-GNC 마그네슘 
1캡슐당 250mg으로 함량이 굉장히 높다.

-쏜리서치 칼슘-마그네슘 말레이트 캡슐
1캡슐당 100mg 함량(각종 위장 장애 및 알러지 반응이 적어 장이 예민한 사람들에게 효과적)

3.철분
-권장량
성인 남자: 9~10mg
성인 여자: 8~14mg
임산부: 하루 24mg
최대 허용량: 45mg

-섭취시간
위가 빈 상태인 공복에 먹는 게 좋다. 식사 30분 전 혹은 식사 2시간 후에 먹는 것이 효과적이다.

-네추럴라이즈 액티브 철분
1정당 30mg으로 철분 함량이 엄청 높다.

-나우푸드 철분 18mg 베지 캡슐
1정당 18mg으로 함량이 적고 위장 장애가 적다.

4.칼슘
-권장량
20세 이상 남녀: 700mg
50세 이상 여자: 800mg
청소년: 800~900mg
전문가들이 권하는 하루 칼슘 최대 섭취량은 2500mg이다.
하루 권장량 이상을 섭취해야 효과를 볼 수 있고 영양제로 섭취할 때는 한 번에 500mg 이하로 여러 번 나누어 먹는 것이 좋다.

-섭취시간
저녁에 칼슘을 섭취하면 숙면을 취하는 데 도움이 되고 식사 후 나오는 위산과 만나서 흡수율도 높아진다.

-솔가 칼슘 600 타블렛
하루 2정 섭취로 2정에 1200mg을 함량하고 함량이 높다.

-레인보우라이트 칼슘 타블렛
1정당 500mg 함량으로 함량이 적다.

5. 오메가3
- 원하는 효과에 따른 권장량
혈중 중성 지질 개선: 500~2,000mg
혈행 개선: 500~2,000mg
건조한 눈 개선: 600~1,000mg
기억력 개선: 900~2,000mg
종합적인 효과는 1000mg정도, 집중적인 효과는 2000mg정도

- 섭취시간
오메가 3는 지용성 영양성분이기 때문에 지방이 많이 들어있는 식사 후 먹는 것이 흡수욜을 높임
공복에 오메가3을 섭취하게 되면 비린 냄새가 강하게 느껴지고 메스꺼움이 있을 수도 있기 때문에, 식후에 따뜻한 물과 함께 섭취하는 것을 권장

- 트리프 스트렝스 오메가3 피쉬오일 알래스카오메가
1캡슐 중 1250mg 중 EPA+DHA는 950mg으로 순도가 약 76%정도로 높다.

-(종근당건강)혈행건강 프로메가 알티지 오메가3 듀얼
2캡슐 1040mg 중 EPA+DHA는 600mg이므로 순도가 약 58%정도로 낮은 편이다.

6. 종합비타민
-권장량
비타민 A(레티놀): 5,000IU (일일 최적 섭취량 5,000~10,000IU)

비타민 B

비타민 B1(티아민): 1.2 ~ 1.4mg (임신, 수유기에는 1.4mg)
비타민 B2(리보플라빈): 1.2 ∼ 1.6mg
비타민 B3(나이아신): 12 ~ 18mg
비타민 B5(판토텐산): 10mg
비타민 B6(피리독신): 1.6 ~ 2.0mg
비타민 B7(비오틴): 30 ~ 100 mcg
비타민 B9(엽산): 400mcg (임신, 수유기에는 1.5~2배)
비타민 B12(코발라민): 2.4mcg
비타민 C(아스코르빈산): 100mg (임신부 110mg, 수유부 135mg, 흡연자 130mg)

비타민 D(콜레칼시페롤): 70세 이상 800IU, 그 이하 연령 600IU

비타민 E(토코페롤): 200 ~ 1,200IU

비타민 K(피토메나디온): 성인 여성 90 mcg, 성인 남성 120mcg
-섭취 시기
활력이 좋아지기 때문에 아침 식후에 먹는 것이 좋고 아침을 안 먹으면 점심 식사 후에 먹는 것이 좋다.

- 나우푸드 데일리 비츠 멀티비타민
비타민A, C,D,E,루테인, 라이코펜 등 함유, 하루 한 알 섭취로 평균 130%함량으로 하루 권장량을 넘긴다.

- 쏜리서치 종합비타민 투퍼데이
하루 2알 섭취로 품질이 좋고 성분이 다양하며 흡수가 잘된다. 함유량이 상대적으로 적다.

**Comment by mondayy1** [comment]
체고!

**Comment by snsthqhr** [comment]
야무진 조사 좋습니다
