### ISSUE TITLE
html에서 이미지 중간에 배치하는 방법 아시나요?

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#42]
![image](https://github.com/snsthqhr/opensauce/assets/74997069/1e8e0ecd-b964-485b-933a-7463a08691d8)
사진에서 구역1블록을 화면가운데 배치하고 싶은데 어떻게 하는지 아시나요? 아시면 도움좀 부탁드립니다

**Comment by snsthqhr** [comment]
![image](https://github.com/snsthqhr/opensauce/assets/74997069/ea0b513a-251b-42ab-a289-caa75cbd5fbc)
이렇게 전체화면으로 했을때는 중앙에 배치되는데 
![image](https://github.com/snsthqhr/opensauce/assets/74997069/528cbcb6-9116-4bcd-aeb6-cc557aa02fab)
전체체화면이 아닐때는 이렇게 위치가 이상해지네요

**Comment by eunseongy** [comment]
코드를 보면 설명해드릴 수 있을 것 같아요

**Comment by snsthqhr** [comment]
해결완료
