### ISSUE TITLE
수정한 홈페이지 디자인

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#45]
![image](https://github.com/snsthqhr/opensauce/assets/128560366/4fd47138-77a7-4421-b468-86e56789f247)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/774f2c76-98fd-4de9-b56f-31e57cd5c4ce)

홈페이지 디자인 수정했습니다.

**Comment by snsthqhr** [comment]
너무 좋습니다. 메인으로 머지 한번해주시면 조사페이지도 변경하겠습니다.
