### ISSUE TITLE
css파일 충돌이 있는거 같습니다.

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#49]
background.css랑 homepagestyle.css에 같은 이름의 클래스가있는거 같습니다. 두개의 css를 적용하는 diagonosis_result페이지에서 충돌이 발생하는데, background에 있는 container  이름 수정하겠습니다.

**Comment by eunseongy** [comment]
넵 확인했습니다. 이제 잘 되네요
