### ISSUE TITLE
pull request 문제 해결

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#60]
![image](https://github.com/snsthqhr/opensauce/assets/128560366/f4812896-8ae9-4f2e-b3e8-f6359e5db4ed)
`<<<<<<<`, `=======`, `>>>>>>>`를 삭제하고 mark as resolved을 누르시고 merge로 병합해주시면 됩니다.

**Comment by mondayy1** [comment]
제가 지우고 merge시키겠습니다~!
