### ISSUE TITLE
여장신 메인 홈페이지

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#61]
![image](https://github.com/snsthqhr/opensauce/assets/128560366/36514e47-1608-412c-a788-bb93369808d4)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/66d1a861-a276-466f-9860-48bb7d6dea3d)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/f39bc482-9298-42bb-aeea-6b618b7b7f99)

최종본입니다. 수정할 거 있으면 알려주세요

**Comment by snsthqhr** [comment]
추천받은 영양제 구매하는 사이트연결 결과페이지 추가하겠습니다 따봉

**Comment by mondayy1** [comment]
좋습니다!
