### ISSUE TITLE
기말 발표 준비

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#62]
6월 10일까지 코드수정 전부 마치고, ppt만들고 대본 만들어야 하는데 오늘 오후에 다들 시간 되시나요?
만나서 진행하는게 빠를거 같습니다

**Comment by snsthqhr** [comment]
오늘 5시이후로 시간되시나요 들

**Comment by eunseongy** [comment]
전 6시에 수업 있어서 8시 반에서 9시에 가능할 것 같습니다.

**Comment by mondayy1** [comment]
목요일에 합시당
