### ISSUE TITLE
영양제 필요성 페이지 디자인

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#64]
![image](https://github.com/snsthqhr/opensauce/assets/128560366/dc21f31a-7498-4102-9c6f-9bd421d448b6)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/7cd8f2aa-ff93-49a9-b540-fef5f740f68a)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/766ca2ba-21a3-498d-ab85-efd9b72c6050)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/ad05822e-bc0e-4cd1-91c4-ba78e5d28f12)
영양제 필요성 페이지입니다. 수정할 거 있으면 말해주세요

**Comment by snsthqhr** [comment]
깔끔하니 보기 좋습니다
