### ISSUE TITLE
영양소 결핍 시 문제 페이지 디자인

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#65]
![image](https://github.com/snsthqhr/opensauce/assets/128560366/58f7f8b5-e6e4-48fe-bd5e-10ce996efaee)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/8584b3e3-34b7-43e9-8bc2-5cb19a1b0d02)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/b90d8fc0-d2fe-4dea-b7b1-44698ee95507)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/7082d780-06b5-42c1-aad7-52ae86dbfcc6)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/4b720c32-d1d6-4ee9-838d-4701d69fa662)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/adfd67e8-e4ce-4062-a65f-be22701756ef)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/abedf347-c5cd-41e1-b965-8e2273d582d8)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/6d23dc02-5868-48ff-9814-392bdf5ea416)
![image](https://github.com/snsthqhr/opensauce/assets/128560366/b61ef296-94b1-419f-ba18-177ed10bbff6)
영양소 결핍 시 문제 페이지 디자인입니다. 추가할 거 있으면 말해주세요

**Comment by mondayy1** [comment]
헉 좋긴한데 너무 길어요 ㅠ 페이지별로 따로 html을 만들어서 연동시키는건 어떨까요...

**Comment by eunseongy** [comment]
그러면 너무 페이지가 많아질 거 같아서 그냥 하는 게 좋을 거 같아요
