### ISSUE TITLE
css 파일 디렉토리 변경

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#67]
현재 css파일들이 template폴더 안에 html파일들이랑 같이 있는데

따로 static폴더를 만들어서 링킹 시키겠습니다.

앞으로 css파일이나 이미지파일들은 static 폴더에서 작업합시다!

**Comment by eunseongy** [comment]
넵 static 폴더에서 css랑 이미지 이용하겠습니다.
