### ISSUE TITLE
main에서 각자 작업할 브랜치로 pull 받을때 유의사항

### ISSUE THREAD

**Issue by mondayy1** [snsthqhr/opensauce#71]
아마 master브랜치에서 pull 받을 때 정책 변경사항 때문에 기본적으로 풀 받으면 invalid라고 뜰겁니다.

그럴 때

```BASH
git config pull.rebase false
```

입력해 주시고 풀 받으면 될겁니다!
세션 종료 후에는 설정이 풀리기 때문에 설정 유지하시려면

```BASH
git config --global pull.rebase false
```

글로벌로 설정하시면 댑니다~

**Comment by eunseongy** [comment]
넵 감사합니다. 덕분에 풀 잘 받았습니다.
