### ISSUE TITLE
웹사이트 디자인

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#8]
![image](https://user-images.githubusercontent.com/128560366/231941590-55f79871-7616-4c36-ad45-53d74cabc612.png)

이런 식으로 처음 웹사이트 홈페이지를 디자인하려고 합니다.

**Comment by mondayy1** [comment]
좋습니다 배경사진 야무진걸로 해서 가시죠

**Comment by eunseongy** [comment]
![image](https://user-images.githubusercontent.com/128560366/231991978-ebc198ec-5daf-4399-a597-8ff41394a8ff.png)
이런 식으로 수정해서 디자인했습니다.

**Comment by snsthqhr** [comment]
보기 좋습니다. go 버튼 모양만 좀 더 수정 해보면 좋을거 같아요. 
배경에 쓰인 이미지소스 좀 공유 해 줄 수 있을까요? 설문조사 페이지에 넣으면 좋을거 같아요

**Comment by eunseongy** [comment]
넵 이미지 주소입니다.  @snsthqhr 
 https://media.istockphoto.com/id/1306511017/ko/%EC%82%AC%EC%A7%84/%EA%B1%B4%EA%B0%95%ED%95%9C-%EC%9D%8C%EC%8B%9D-%EB%B0%B0%EA%B2%BD-%ED%9D%B0%EC%83%89-%EB%B3%B5%EC%82%AC-%EA%B3%B5%EA%B0%84-%EB%B0%B0%EB%84%88%EC%97%90-%EC%A2%85%EC%9D%B4-%EA%B0%80%EB%B0%A9-%EC%95%BC%EC%B1%84%EC%99%80-%EA%B3%BC%EC%9D%BC%EC%97%90-%EA%B1%B4%EA%B0%95%ED%95%9C-%EC%B1%84%EC%8B%9D-%EC%A3%BC%EC%9D%98-%EC%B1%84%EC%8B%9D-%EC%A3%BC%EC%9D%98-%EC%9E%90-%EC%9D%8C%EC%8B%9D-%EC%87%BC%ED%95%91-%EC%8B%9D%ED%92%88-%EC%8A%88%ED%8D%BC%EB%A7%88%EC%BC%93-%EA%B3%BC-%EA%B9%A8%EB%81%97%ED%95%9C-%EB%B9%84%EA%B1%B4-%EB%A8%B9%EB%8A%94-%EA%B0%9C%EB%85%90.jpg?b=1&s=170667a&w=0&k=20&c=-Ws3to9OHGntwCNU3peCmv4wqN58aeOgqJDrdqtgiPM

**Comment by snsthqhr** [comment]
![image](https://user-images.githubusercontent.com/74997069/232208192-0354500e-d688-4fbf-b9e1-9f46f7ce24d8.png)
받은 이미지를 토대로 설문조사 페이지 작성했습니다. 설문조사 페이지 꾸미는건 5월에 할게요!
