### ISSUE TITLE
여장신 소개 페이지 수정

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#82]
여장신 소개 페이지에서 소개 멘트를 일부 수정하였습니다.
 아래는 수정 내용입니다.        
         AI기반으로 개인에게 적합한 영양제를 추천해주는 사이트입니다.
         AI는 chatgpt api를 사용했고 평소의 식습관, 몸의 상태와 증상들을 설문조사를 통해 입력받아 
         부족한 영양소를 찾아내어 그에 맞는 영양제를 추천해드립니다. 
         입력받은 데이터를 통해 영양제 중 함유량이 많은 것이 적합한 지 적은 것이 적합한 지 정하고 
         시중에 있는 영양제들 중 평가가 좋은 영양제를 하나 직접 선정하여 개인에게 알맞게 추천해드립니다.

**Comment by snsthqhr** [comment]
간략하게 지금 내용 좋은거같아요
