### ISSUE TITLE
결과 진단 홈페이지 디자인 추가

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#83]
메인 홈페이지에 있는 판매 사이트 바로 가기를 결과 홈페이지에도 추가해서 소비자들이 바로 이용하실 수 있게 하는 건 어떨까요?

**Comment by snsthqhr** [comment]
좋은거 같아요!

**Comment by mondayy1** [comment]
좋습니다. 하단부 통일하는 아이디어 좋습니다.
