### ISSUE TITLE
기말 ppt

### ISSUE THREAD

**Issue by eunseongy** [snsthqhr/opensauce#84]
기말 ppt에는 중간 발표에 비교해서 어떤 것을 추가하면 좋을까요? 저희 구현상황은 저번처럼 영상으로 남기면 될 것 같아요

**Comment by snsthqhr** [comment]
시연영상, 여장신 설명하는 페이지에 대한 설명 추가하겠습니다

**Comment by eunseongy** [comment]
https://1drv.ms/p/s!Avdv8DYOo0G6qUBRZHxzoAO_cOT7?e=UCpQ87 
여기서 작업 같이 하면 될 것 같습니다.

**Comment by eunseongy** [comment]
https://docs.google.com/presentation/d/1Y-BdyniPJADVxjckEtHIQXTJRYqXG7aaC5bG2_jtqcY/edit#slide=id.g118d152111a_0_426
여기로 바꼈습니다.
