### ISSUE TITLE
결과페이지 링크 버튼 양식통일

### ISSUE THREAD

**Issue by snsthqhr** [snsthqhr/opensauce#87]
![image](https://github.com/snsthqhr/opensauce/assets/74997069/c2d64f3a-d48b-4c7b-8de0-34c2bc3592fb)
홈페이지로 돌아가기 버튼이랑 홈페이지로 돌아가는 버튼 색깔 다른데, 이대로 진행해도 괜찮을까요?

**Comment by eunseongy** [comment]
네 상관없을 것 같아요.

**Comment by snsthqhr** [comment]
그럼 이대로 진행할게요!
